# Html5BoilerplateHelper will first check your ENV and
# then this yml file for these values. If they are both
# empty, the google code block will not be used.
#
# e.g. ENV['GOOGLE_ACCOUNT_ID'] || yml[:google_account_id]
# e.g. ENV['GOOGLE_API_KEY'] || yml[:google_api_key]
#
defaults: &defaults
  :google_account_id: 'UA-25781377-1'
  :google_api_key: 'ABQIAAAAxGe-p_bEmJ4AkZYoP55gIRQlUCnzJKwJlbBI2Cn4jnra0GV6IRRR6V5jA3wz06lJjRz6ZNjpV-t0Wg'

:development:
  <<: *defaults

:test:
  <<: *defaults

:staging:
  <<: *defaults

:production:
  <<: *defaults
